spring:
  application:
    name: msj-order
  profiles:
    active: dev,mapper,redis
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: msj-order
server:
  port: 9104
feign:
  hystrix:
    #使断路器起作用
    enabled: true
#把sql语句打印到控制台
#logging:
#  level:
#    com:
#     qiqi:
#      msjmapper:
#        mapper: DEBUG

---
spring:
  profiles: dev

---
spring:
  profiles: prod