spring:
  profiles:
    active: dev,redis,mapper
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: msj-api
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: msj-api
#  data:
#    solr:
#      host: http://127.0.0.1:8983/solr
server:
#  ssl:
#    key-store: msj-api/server.keystore
#    key-store-password: 77jiajia
#    key-store-type: JKS
#    key-alias: meishijia
#    key-password: meishijia

#    trust-store: server.keystore
#    trust-store-password: 77jiajia
#    enabled: true
#    client-auth: need
  port: 9101

---
spring:
  profiles: dev

---
spring:
  profiles: prod