server:
  port: 8090
spring:
  profiles:
    active: dev,mapper
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      content-type: text/html