server:
  port: 8090
spring:
  profiles:
    active: dev,mapper
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      content-type: text/html
  devtools:
      restart:
        enabled: false
        exclude: static/**,templates/**
  jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8