spring:
  application:
    name: cloud-zuul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: cloud-zuul
server:
  port: 9003
zuul:
  routes:
    producer:
      path: /producer/**
      serviceId: eureka-producer
    consumer:
      path: /consumer/**
      serviceId: eureka-consumer
  #是否开启重试功能
  retryable: true
ribbon:
  #对当前服务的重试次数
  MaxAutoRetries: 2
  #切换相同Server的次数
  MaxAutoRetriesNextServer: 0
