spring:
  application:
    name: msj-football
  profiles:
    active: dev,mapper,redis
  cloud:
      consul:
        host: localhost
        port: 8500
        discovery:
          service-name: msj-football

server:
  port: 9102

---
spring:
  profiles: dev

---
spring:
  profiles: prod